CREATE TABLE IF NOT EXISTS trade_simulado (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    run_id VARCHAR(32) NOT NULL,
    strategy_lane VARCHAR(16) NOT NULL DEFAULT 'LEGACY',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    strategy_minutes INT NOT NULL,
    threshold_pct DECIMAL(8, 4) NOT NULL,
    initial_balance DECIMAL(20, 8) NOT NULL DEFAULT 100.00000000,
    balance_before DECIMAL(20, 8) NOT NULL,
    balance_after DECIMAL(20, 8) NOT NULL,
    entry_time DATETIME NOT NULL,
    exit_time DATETIME NOT NULL,
    side ENUM('LONG','SHORT') NOT NULL,
    entry_price DECIMAL(20, 8) NOT NULL,
    exit_price DECIMAL(20, 8) NOT NULL,
    btc_return_pct DECIMAL(12, 6) NOT NULL,
    trade_return_pct DECIMAL(12, 6) NOT NULL,
    pnl_usd DECIMAL(20, 8) NOT NULL,
    predicted_label TINYINT NOT NULL,
    actual_label TINYINT NOT NULL,
    was_correct TINYINT(1) NOT NULL DEFAULT 0,
    neighbors_count INT NOT NULL DEFAULT 0,
    similarity DECIMAL(10, 6) NULL,
    probability_up DECIMAL(10, 6) NOT NULL DEFAULT 0,
    probability_flat DECIMAL(10, 6) NOT NULL DEFAULT 0,
    probability_down DECIMAL(10, 6) NOT NULL DEFAULT 0,
    notes VARCHAR(255) NULL,
    PRIMARY KEY (id),
    KEY idx_run_id (run_id),
    KEY idx_strategy_lane (strategy_lane),
    KEY idx_entry_time (entry_time),
    KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
